export const FETCH_SEARCH = 'FETCH_SEARCH';
export const FETCH_SEARCH_FULFILLED = 'FETCH_SEARCH_FULLFILLED';
export const FETCH_SEARCH_ERROR = 'FETCH_SEARCH_ERROR';
export const FETCH_SEARCH_REJECTED = 'FETCH_SEARCH_REJECTED';
export const CLOSE_ERROR = 'CLOSE_ERROR'